# Generated by Django 4.0.5 on 2022-06-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20220629_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='wechat',
            field=models.CharField(max_length=25, null=True, verbose_name='微信号'),
        ),
    ]
