# Generated by Django 4.0.5 on 2022-06-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_usermodel_wechat'),
    ]

    operations = [
    ]
