# Generated by Django 4.0.5 on 2022-06-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_usermodel_avatar_usermodel_phone_and_more'),
    ]

    operations = [
    ]
