# Generated by Django 4.0.5 on 2022-06-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_usermodel_qq_alter_usermodel_avatar'),
    ]

    operations = [
    ]
