# Generated by Django 4.0.5 on 2022-06-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_auto_20220629_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_uuid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
